pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
    - job:
      steps:
        - task: UseGitVersion@5
          displayName: GitVersion
          inputs:
            versionSpec: '5.x'
            
        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: build
            arguments: '--configuration $(BuildConfiguration) --verbosity normal'
          env:
            Version: $(GitVersion.SemVer)
          
        - task: DotNetCoreCLI@2
          displayName: Test
          inputs:
            command: test
            arguments: '--configuration $(BuildConfiguration) --no-build --verbosity normal'
          env:
            AadAuth:Password: $(AadAuth:Password)
            Version: $(GitVersion.SemVer)
            
        - task: DotNetCoreCLI@2
          displayName: Pack
          inputs:
            command: pack
            verbosityPack: normal
            packagesToPack: '*.sln'
            configurationToPack: Release
            nobuild: true
          env:
            Version: $(GitVersion.SemVer)
          
        - task: DotNetCoreCLI@2
          displayName: Publish
          inputs:
            command: publish
            publishWebProjects: false
            modifyOutputPath: true
          env:
            Version: $(GitVersion.SemVer)
          
        - task: PublishPipelineArtifact@1
          displayName: Publish Pipeline Artifacts
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)'
            publishLocation: 'pipeline'
          condition: always()

  - stage: Deploy
    jobs:
    - deployment: NuGet
      environment: NuGet
      strategy: 
        runOnce:
          deploy:          
            steps:
            - task: NuGetCommand@2
              displayName: Push
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg'
                nuGetFeedType: 'external'
                publishFeedCredentials: 'nuget.org'
