pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: 'Release'
  Verbosity: 'normal'

stages:
  - stage: Build
    jobs:
    - job:
      steps:
        - task: UseGitVersion@5
          displayName: GitVersion
          inputs:
            versionSpec: '5.x'
            
        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: build
            arguments: '--configuration $(BuildConfiguration) --verbosity $(Verbosity)'
          env:
            Version: $(GitVersion.SemVer)
          
        - task: DotNetCoreCLI@2
          displayName: Test
          inputs:
            command: test
            arguments: '--configuration $(BuildConfiguration) --no-build --verbosity $(Verbosity)'
          env:
            Version: $(GitVersion.SemVer)
            AadAuth:Password: $(AadAuth:Password)
            
        - task: DotNetCoreCLI@2
          displayName: Pack
          inputs:
            command: pack
            verbosityPack: $(Verbosity)
            packagesToPack: '*.sln'
            configurationToPack: $(BuildConfiguration)
            nobuild: true
          env:
            Version: $(GitVersion.SemVer)
          
        - task: DotNetCoreCLI@2
          displayName: Publish
          inputs:
            command: publish
            arguments: '--configuration $(BuildConfiguration) --no-build --verbosity $(Verbosity) -o $(Build.ArtifactStagingDirectory)'
            publishWebProjects: false
            zipAfterPublish: false
            modifyOutputPath: true
          env:
            Version: $(GitVersion.SemVer)
            
        - task: PublishPipelineArtifact@1
          displayName: Publish Pipeline Artifacts
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)'
            publishLocation: 'pipeline'
          condition: always()

  - stage: DeployNuGet
    dependsOn: 
      - Build
    jobs:
    - deployment: NuGet
      environment: NuGet
      strategy: 
        runOnce:
          deploy:          
            steps:
            - task: NuGetCommand@2
              displayName: Push
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg'
                nuGetFeedType: 'external'
                publishFeedCredentials: 'nuget.org'

  - stage: DeployAzureArtifacts
    dependsOn: 
      - Build
    jobs:
    - deployment: AzureArtifacts
      environment: AzureArtifacts
      strategy: 
        runOnce:
          deploy:          
            steps:
            - task: DotNetCoreCLI@2
              displayName: Push
              inputs:
                command: 'push'
                searchPatternPush: '$(Pipeline.Workspace)/**/*.nupkg'
                feedPublish: 'simeoncloud'